[package]
name = "cppmm-build"
version = "0.1.0"
edition = "2018"
description="Build utilities for cppmm-based projects"
license="BSD-3-Clause"
authors = ["Anders Langlands <anderslanglands@gmail.com>"]


[dependencies]
cmake = "0.1.45"
regex = "1.5.4"
quick-xml = "0.22.0"
